### ISSUE TITLE
JavaScript error on loading codemirror editors

### ISSUE THREAD

**Issue by etruel** [etruel/wpematico-custom-hooks#3]
![imagen](https://user-images.githubusercontent.com/3663229/108604299-d2d8bd00-738b-11eb-9614-67eeda9693fb.png)

Chequear el error si aparece en Settings al cambiar de editor con el select o al intentar grabar.

**Comment by asuajeivan** [comment]
Estuve realizando una busqueda de este error, Intente cambiando el thema del editor guardando y revisando todas las pestañas del settings y la consola.

Probé también con algunos hooks, guardándolos y revisando de nuevo el settings, no encontré nada extraño.

**Comment by etruel** [comment]
Tal vez sean las librerías codemirror instaladas que usamos para esa feature.
¿También puede ser el JavaScript ese wpehk_settings.js
probaste desde el inspector seguir el debug en ese archivo js ?

**Comment by asuajeivan** [comment]
Estuve realizando el debug del archivo wpehk_settings.js con el inspector de Mozilla Firefox y todo esta bien, coloque breakpoints en las líneas 170 y 20, todo funciono como debe ser, investigue un poco sobre el método trace() de la consola, hice un debug con ese método y no pude ver ningún mensaje de error.

**Comment by etruel** [comment]
El error ya no sale pero falta que resalte el texto PHP enriquecido. 
Ver si es necesario actualizar las librerías desde https://codemirror.net/doc/manual.html#overview
